components/order-chat.tsx

Fixed the display of the messages from the counterparty.

farrah/fix: chat message

---

app/ads/page.tsx
app/orders/[id]/page.tsx
app/orders/page.tsx
app/profile/page.tsx
components/navigation.tsx
components/order-chat.tsx
services/api/api-orders.ts

Implemented the attachment when sending a chat message.

farrah/fix: implement chat attachment

---

app/advertiser/[id]/page.tsx

Fixed the values for advertisers' stats.

farrah/fix: advertiser stats

---

lib/local-variables.ts

fix: create env for tokens

---

app/page.tsx
services/api/api-buy-sell.ts

Fixed the display of user rating.

farrah/fix: user rating

---

app/page.tsx

Fixed the user rating average.

fix: user rating average

---

app/orders/[id]/page.tsx
app/orders/page.tsx
components/buy-sell/order-sidebar.tsx

farrah/fix: bugs

---

app/orders/[id]/page.tsx
app/orders/page.tsx
app/page.tsx
components/order-details-sidebar.tsx
services/api/api-orders.ts

farrah/fix: buy-sell-order

---

components/buy-sell/order-sidebar.tsx

farrah/fix: order sidebar

---

components/buy-sell/order-sidebar.tsx

Implemented the design changes on order placing.

farrah/fix: buy-sell design

---

components/buy-sell/order-sidebar.tsx

Break long words in instructions.

farrah/fix: word wrap

---

app/advertiser/[id]/page.tsx

Fixed listing of adverts on advertiser page.

fix: advertiser page

---

app/advertiser/[id]/page.tsx
app/page.tsx
components/buy-sell/order-sidebar.tsx
components/ui/button.tsx

farrah/fix: buttons

---

eslint.config.mjs

fix: eslint errors

---

app/ads/components/ad-details-form.tsx
app/ads/components/mobile-my-ads-list.tsx
app/ads/components/my-ads-header.tsx
app/ads/components/my-ads-table.tsx
app/ads/components/payment-details-form.tsx
app/ads/components/ui/currency-input.tsx
app/ads/create/page.tsx
app/orders/[id]/page.tsx
app/page.tsx
app/profile/api/api-payment-methods.ts
app/profile/components/payment-methods-tab.tsx
app/profile/components/stats-tabs.tsx
components/MyAdsTable.tsx
components/buy-sell/filter-popup.tsx
components/header.tsx
components/my-ads/my-ads-table.tsx
components/novu-notifications/index.tsx
components/order-chat.tsx
components/profile/business-hours.tsx
components/profile/stats-tabs.tsx
components/profile/user-info.tsx
components/ui/calendar.tsx
components/ui/chart.tsx
components/ui/textarea.tsx
components/ui/use-toast.ts
eslint.config.mjs
lib/websocket.ts
package-lock.json
package.json

farrah/fix: eslint issues

---

components/novu-notifications/index.tsx

Revert "Revert "Notification API fix""

---

app/login/page.tsx
services/api/api-auth.ts

farrah/ fix: socket

---

services/api/api-orders.ts

Fixed the payment methods on buy order.

farrah/fix: pms

---

app/orders/[id]/page.tsx

Reload the order details upon cancelling.

farrah/fix: order details

---

package-lock.json
package.json

Updated lodash version to latest.

fix: updated lodash version

---

.github/workflows/build-and-deploy-prod.yml
.github/workflows/build-and-deploy-staging.yml

Added workflows to deploy to Cloudflare Pages.

farrah/chore: deploy to staging and prod

---

app/ads/components/ad-payment-methods.tsx
app/ads/create/page.tsx
app/ads/page.tsx
app/layout.tsx
app/login/page.tsx
app/orders/page.tsx
app/profile/api/api-payment-methods.ts
app/profile/components/add-payment-method-panel.tsx
app/profile/components/payment-methods-tab.tsx
app/profile/components/stats-tabs.tsx
app/wallet/page.tsx
components/navigation.tsx
components/novu-notifications/index.tsx
components/sidebar.tsx
components/ui/calendar.tsx
components/ui/chart.tsx
components/ui/use-toast.ts
package-lock.json
package.json

farrah/fix: lint issues

---

app/main.tsx
services/api/api-auth.ts

farrah/fix: session

---

app/main.tsx
services/api/api-auth.ts

farrah/fix: login issues

---

app/main.tsx
services/api/api-auth.ts

farrah/fix: login response

---

app/main.tsx
app/profile/page.tsx
components/profile/user-info.tsx
components/sidebar.tsx

Updated the champion links and design.

farrah/fix: champion links and design

---

services/api/api-buy-sell.ts

farrah/fix: header calls

---

services/api/api-auth.ts

farrah/fix: logout

---

app/ads/api/api-ads.ts
app/ads/components/ad-payment-methods.tsx
app/ads/components/payment-details-form.tsx
app/profile/api/api-payment-methods.ts
app/profile/components/payment-methods-tab.tsx
app/profile/components/stats-tabs.tsx
app/profile/page.tsx
app/wallet/components/wallet-balance.tsx
components/profile/stats-tabs.tsx
lib/local-variables.ts
services/api/api-buy-sell.ts
services/api/api-my-ads.ts
services/api/api-orders.ts
services/api/api-profile.ts

farrah/fix: remove auth headers

---

app/login/page.tsx
services/api/api-auth.ts
services/api/api-buy-sell.ts

Get the residence country of a user.

farrah/fix: get country code

---

app/main.tsx
app/page.tsx
lib/local-variables.ts
package-lock.json
package.json
pnpm-lock.yaml

Revert "farrah/ updated the buy-sell page"

---

app/ads/api/api-ads.ts
app/ads/components/payment-details-form.tsx
app/login/page.tsx
app/main.tsx
app/profile/api/api-payment-methods.ts
app/profile/components/payment-methods-tab.tsx
app/profile/components/stats-tabs.tsx
app/profile/page.tsx
app/wallet/components/full-screen-iframe-modal.tsx
app/wallet/components/wallet-balance.tsx
components/header.tsx
components/novu-notifications/index.tsx
components/profile/stats-tabs.tsx
lib/local-variables.ts
services/api/api-auth-prev.ts
services/api/api-buy-sell.ts
services/api/api-my-ads.ts
services/api/api-orders.ts
services/api/api-profile.ts
services/api/index.ts

Added a fallback for development environment.

farrah/fix: add fallback

---

services/api/api-orders.ts

farrah/fix: fallback

---

app/login/page.tsx
components/header.tsx

farrah/fix: api auth

---

app/login/page.tsx

farrah/fix: token

---

components/novu-notifications/index.tsx

farrah/fix: build error

---

app/advertiser/[id]/page.tsx

Updated missing data on advertiser's page.

farrah/fix: advertiser page

---

app/advertiser/[id]/page.tsx

Fixed duration on advertiser's page.

farrah/fix: duration

---

app/page.tsx

Fixed the adverts list on responsive.

farrah/fix: market page

---

app/advertiser/[id]/page.tsx
app/page.tsx
components/empty-state.tsx

Fixed empty ads state on Market and Advertiser pages.

farrah/fix: empty ads

---

app/page.tsx
components/empty-state.tsx

Fixed the adverts list on responsive.

farrah/fix: adverts list

---

app/orders/[id]/page.tsx
app/orders/page.tsx
components/buy-sell/order-sidebar.tsx
components/complaint/complaint-form.tsx
lib/utils.ts

farrah/fix: variants

---

app/advertiser/[id]/page.tsx
app/page.tsx
components/empty-state.tsx

Updated the empty ads message on advertiser's page.

farrah/fix: update empty ads message

---

app/orders/[id]/page.tsx

Fixed the buttons on Orders page.

farrah/fix: orders buttons

---

app/profile/components/payment-methods-tab.tsx
app/profile/components/stats-tabs.tsx
components/profile/user-info.tsx

Fixed Profile page on responsive.

farrah/fix: profile page

---

app/advertiser/[id]/page.tsx
app/page.tsx

farrah/fix: clock icon

---

components/block-confirmation.tsx

farrah/fix: bug

---

app/ads/components/delete-confirmation-dialog.tsx
app/ads/components/mobile-my-ads-list.tsx
app/ads/components/my-ads-mobile-view.tsx
app/ads/components/my-ads-table.tsx
components/MyAdsTable.tsx
components/my-ads/my-ads-table.tsx

Fixed the delete confirmation dialog.

farrah/fix: delete confirmation

---

app/ads/components/delete-confirmation-dialog.tsx
app/ads/components/mobile-my-ads-list.tsx
app/ads/components/my-ads-mobile-view.tsx
components/MyAdsTable.tsx
components/my-ads/my-ads-table.tsx

Fixed the delete notification.

farrah/fix: delete notification

---

services/api/api-buy-sell.ts

farrah/fix: follow advertiser

---

components/order-chat.tsx

Added condition for message tags.

farrah/fix: order chat bug

---

app/ads/create/page.tsx

farrah/fix: loader

---

app/profile/components/add-payment-method-panel.tsx
components/buy-sell/order-sidebar.tsx

Add allowedPaymentMethods prop and filter payment methods accordingly.

farrah/feat: restrict payment methods to buyer's accepted ones for sell orders

---

app/ads/components/ad-details-form.tsx
app/ads/components/payment-details-form.tsx
app/ads/components/shared/multi-step-ad-form.tsx
app/ads/components/shared/progress-steps.tsx

Fixed the bug on creation and updating of ads.

farrah/fix create/update of ads

---

app/orders/[id]/page.tsx
app/profile/components/add-payment-method-panel.tsx
app/profile/components/stats-tabs.tsx
components/complaint/complaint-form.tsx
components/complaint/types.ts
components/profile/user-info.tsx

Fixed bugs on Orders and Profile pages.

farrah/fix bugs on Orders and Profile pages

---

app/ads/components/ad-payment-methods.tsx
app/ads/components/payment-details-form.tsx
app/ads/components/shared/progress-steps.tsx
app/orders/page.tsx
tailwind.config.ts

farrah/fixed Ads page design

---

app/orders/page.tsx
components/novu-notifications/index.tsx

Close the notifications on click and added a label on order details.

farrah/fix: notifications and added a label on order details

---

app/ads/components/payment-method-bottom-sheet.tsx
app/ads/components/shared/multi-step-ad-form.tsx
app/ads/components/shared/order-time-limit-selector.tsx
components/ui/select.tsx

Added order expiry to ad conditions.

farrah/fix: ad conditions

---

app/ads/components/my-ads-table.tsx

Showed an error message when deleting an advert.

farrah/fix: delete advert

---

services/api/api-auth-prev.ts

farrah/fix: update the branch to master

---

app/profile/components/stats-grid.tsx
components/market-filter/market-filter-dropdown.tsx
lib/time-utils.ts

Added tabs for stats and payment methods on Profile page.

farrah/fix: added tabs for stats and payment methods

---

next.config.ts

Updated the nextjs config to export the pages.

farrah/fix: nextjs config

---

app/ads/edit/[id]/page.tsx
app/advertiser/[id]/page.tsx
app/orders/[id]/page.tsx

farrah/fix: export of pages

---

package.json
pnpm-lock.yaml

Fixed the cookie dependencies.

farrah/fix: cookie dependencies

---

package.json
pnpm-lock.yaml
pnpm-workspace.yaml

farrah/fix: next-on-pages

---

.github/workflows/build-and-deploy-staging.yml

farrah/fix: wrangler

---

.github/workflows/build-and-deploy-staging.yml
wrangler.toml

farrah/fix: wrangler config

---

.github/workflows/build-and-deploy-staging.yml

Added staging environment variables.

farrah/fix: add environment variables

---

services/api/api-my-ads.ts

farrah/fix: authorized calls

---

app/wallet/components/transactions-tab.tsx

Update logic to process transaction type based on BE change

Ernest/ Update logic to process transaction type based on BE change

---

app/profile/components/follows-tab.tsx
app/profile/components/stats-tabs.tsx
services/api/api-profile.ts

Added Follows section on Profile page.

farrah/feat: follows section

---

app/advertiser/[id]/page.tsx
app/profile/components/blocked-tab.tsx
app/profile/components/follows-tab.tsx
app/profile/components/stats-tabs.tsx
components/empty-state.tsx
services/api/api-profile.ts

Add Blocked section on Profile page.

farrah/feat:blocked users section

---

.github/workflows/build-and-deploy-prod.yml

Updated the production workflow.

farrah/chore: update build-and-deploy-prod.yml

---

tsconfig.json

farrah/chore: update tsconfig.json

---

package.json
pnpm-lock.yaml

farrah/chore: update package

---

tsconfig.json

farrah/fix: module config

---

vercel.json

farrah/fix: prod workflow

---

.github/workflows/build-and-deploy-staging.yml
lib/local-variables.ts
services/api/api-auth.ts
services/api/api-orders.ts
services/api/api-profile.ts

Connect to deriv staging environment.

farrah/fix: v2 connect

---

lib/websocket.ts

farrah/fix: socket config

---

app/orders/components/date-filter.tsx
app/orders/page.tsx
app/page.tsx
app/profile/components/add-payment-method-panel.tsx
components/buy-sell/order-sidebar.tsx
components/currency-filter/currency-filter.tsx
components/market-filter/market-filter-dropdown.tsx
components/payment-methods-filter/payment-methods-filter.tsx
components/rating-filter/rating-sidebar.tsx
lib/local-variables.ts
package.json
pnpm-lock.yaml
vercel.json

Updated the Market and Orders pages to the latest design.

farrah/fix: market and orders pages

---

services/api/api-auth.ts

Added the branch and data-source.

farrah/fix: branch

---

components/novu-notifications/index.tsx
lib/local-variables.ts

farrah/fix: updated url

---

vercel.json

farrah/chore: update vercel config

---

vercel.json

farrah/fix: update vercel.json

---

app/ads/page.tsx
app/profile/components/payment-methods-tab.tsx
app/profile/components/user-info.tsx
app/profile/page.tsx
components/kyc-onboarding-sheet/kyc-onboarding-sheet.tsx

farrah/fix: user onboarding

---

vercel.json

farrah/fix: vercel config

---

app/ads/page.tsx
vercel.json

Fixed the bug on load of Ads page.

farrah/fix: bug on loading the ads list

---

app/ads/page.tsx

farrah/fix: bug on Ads page

---

__tests__/components/balance-section.test.tsx
app/ads/components/my-ads-table.tsx
app/orders/page.tsx
app/page.tsx
app/profile/components/stats-grid.tsx
app/profile/components/trade-limits.tsx
components/balance-section/balance-section.tsx
components/balance-section/index.ts
components/buy-sell/order-sidebar.tsx
services/api/api-auth.ts
vercel.json

Added user's balance on Market page Formatted amounts on all pages.

farrah/ fix: add balance on Market page 

---

app/ads/components/ad-payment-methods.tsx
app/profile/components/add-payment-method-panel.tsx
app/profile/components/stats-tabs.tsx
components/buy-sell/order-sidebar.tsx
vercel.json

Updated the component for showing the payment methods.

farrah/fix: payment method panel

---

components/order-chat.tsx
vercel.json

Updated the design of chat messages.

farrah/fix: order chat design
